### PR TITLE
Fix regression bugs due to recent 'react-tag-autocomplete' v6 uplift

### LINKED ISSUE #1360: styling issue creating a pulse entry
**Describe the bug**
Drop-down options not working as expected. For Tags, I cannot select the appropriate choice, and for author, I cannot delete the wrong choice. Something strange also happened when I uploaded the image. Can't save (not an option), but refreshed (lost work) and now still seeing the same issue only without text.

Screen Shot 2020-07-02 at 11 52 27 AM
Screen Shot 2020-07-02 at 12 10 27 PM
Screen Shot 2020-07-02 at 11 54 51 AM
Screen Shot 2020-07-02 at 11 52 33 AM

**Expected behavior**
Expected to be able to type and edit in dropdown fields. I also expected a refresh to fix it, but it did not.

**Desktop (please complete the following information):**
 - OS: MacOS Catalina 10.15.5
 - Firefox 77.0.1 (64-bit)

**Additional context**
I haven't changed anything in my browser settings since I last created a pulse entry (without these complications)

### PR DESCRIPTION
**Pull request by mmmavis**
Fixed #1360 

I should have been more careful with that Dependabot PR & visited the official `'react-tag-autocomplete` repo for more detailed docs before upgrading that library to v6. 

Note that autocomplete doesn't work for the "creator" field due to an API bug. I've filed a ticket on the API repo.

### CODE REVIEW

File: pages/add/form/auto-complete-input.js [hunk 1]
```diff
@@ -159,12 +159,11 @@ export default class AutoCompleteInput extends Component {
...
-          autofocus={false}
           delimiters={DELIMITERS}
-          handleDelete={(...args) => this.handleDelete(...args)}
-          handleAddition={(...args) => this.handleAddition(...args)}
-          handleInputChange={(...args) => this.handleInputChange(...args)}
-          placeholder={placeholder}
+          onDelete={(...args) => this.handleDelete(...args)}
+          onAddition={(...args) => this.handleAddition(...args)}
+          onInput={(...args) => this.handleInputChange(...args)}
+          placeholderText={placeholder}
```
Comment (mmmavis) [inline pages/add/form/auto-complete-input.js:166]: These props have been renamed.

File: pages/add/form/detail-info-fields.js [hunk 2]
```diff
@@ -26,7 +26,7 @@ export default {
   },
   related_creators: {
     type: Creators,
-    label: `Name any creators, contributors, partners. Comma separated.`,
+    label: `Name any creators, contributors, partners. Tab separated.`,
```
Comment (mmmavis) [inline pages/add/form/detail-info-fields.js:29]: Comma is no longer supported for some reason. I have filed a ticket on the library's repo.

See https://github.com/mozilla/network-pulse/pull/1364/files#diff-3f3823e4d9a300e71bad95c88168c569

File: pages/add/form/auto-complete-input.js [hunk 3]
```diff
@@ -159,12 +159,11 @@ export default class AutoCompleteInput extends Component {
           tags={this.state.data}
           suggestions={this.getFilteredSuggestions()}
           allowNew={true}
-          autofocus={false}
```
Comment (mmmavis) [inline pages/add/form/auto-complete-input.js:162]: This is no longer supported.

File: pages/add/form/detail-info-fields.js (hunk 2 above)
Comment (Pomax) [reply pages/add/form/detail-info-fields.js:29]: This is a list that we can specify (see https://github.com/i-like-robots/react-tags/blob/master/README.md#delimiters-optional) so instead of rewriting this code to advocate tabs, let's keep all of this the same but make sure to specify a `<ReactTags delimiters={[',']} ...>` ourselves.

Comment (Pomax) [reply pages/add/form/detail-info-fields.js:29]:
```suggestion
    label: `Name any creators, contributors, partners. comma-separated.`,
```

File: pages/add/form/detail-info-fields.js [hunk 4]
```diff
@@ -43,7 +43,7 @@ export default {
   },
   tags: {
     type: Tags,
-    label: `Tags: Comma separated. Spaces are ok. Issues are added automatically.`,
+    label: `Tags: Tab separated. Spaces are ok. Issues are added automatically.`,
```
Comment (Pomax) [inline pages/add/form/detail-info-fields.js:46]:
```suggestion
    label: `Tags: Comma-separated. Spaces are ok. Issues are added automatically.`,
```

File: pages/add/form/tag-delimiters.js [hunk 5]
```diff
@@ -1,4 +1,10 @@
 // keycodes for tab,enter,comma, used with
 // the react-tags-autocomplete component
-const DELIMITERS = [9, 13, 188];
+// The delimiters option is now an array of KeyboardEvent.key values and
+// not KeyboardEvent.keyCode codes,
+// e.g. [13, 9] should now be written as ['Enter', 'Tab']. See https://keycode.info/ for more information.
+
+// It seems like react-tags-autocomplete no longer accepts Comma as delimiter
+// GitHub ticket filed: https://github.com/i-like-robots/react-tags/issues/213
+const DELIMITERS = [`Tab`, `Enter`];
```
Comment (Pomax) [inline pages/add/form/tag-delimiters.js:9]:
```suggestion
const DELIMITERS = [`Tab`, `Enter`, `,`];
```

File: pages/add/form/tag-delimiters.js [hunk 6]
```diff
@@ -1,4 +1,10 @@
 // keycodes for tab,enter,comma, used with
 // the react-tags-autocomplete component
-const DELIMITERS = [9, 13, 188];
+// The delimiters option is now an array of KeyboardEvent.key values and
+// not KeyboardEvent.keyCode codes,
+// e.g. [13, 9] should now be written as ['Enter', 'Tab']. See https://keycode.info/ for more information.
+
+// It seems like react-tags-autocomplete no longer accepts Comma as delimiter
+// GitHub ticket filed: https://github.com/i-like-robots/react-tags/issues/213
```
Comment (Pomax) [inline pages/add/form/tag-delimiters.js:8]:
```suggestion
// Delimiters map to `KeyboardEvent.key` values, see https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key/Key_Values
```

File: pages/add/form/auto-complete-input.js (hunk 3 above)
Comment (Pomax) [reply pages/add/form/auto-complete-input.js:162]: It took me a while to convince them, but I'm glad they finally removed it.

Comment (mmmavis) [reply pages/add/form/auto-complete-input.js:162]: Yay!
